name: Docker Build & Publish

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Clone rpository
        uses: actions/checkout@v4

      - name: Login to DOCKER
        run: docker login -u "${{ secrets.DOCKER_USERNAME }}" -p "${{ secrets.DOCKER_PASSWORD }}"

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/todo-api:${{ github.sha }} -f ./Dockerfile .

      - name: Tag latest
        run: docker tag ${{ secrets.DOCKER_USERNAME }}/todo-api:${{ github.sha }} ${{ secrets.DOCKER_USERNAME }}/todo-api:latest

      - name: Push Docker image
        run: |   
          docker push ${{ secrets.DOCKER_USERNAME }}/todo-api:${{ github.sha }} 
          docker push ${{ secrets.DOCKER_USERNAME }}/todo-api:latest
        